name = 'whentho-api-development'
type = 'webpack'
account_id = 'f662588e1b414d6188fce196fd7e6d66'
zone_id = '504b4d349429345f123b3736d588c034'
route = 'https://api-development.whentho.xyz/*'
[env.staging]
name = 'whentho-api-staging'
route = 'https://api-staging.whentho.xyz/*'

[env.production]
name = 'whentho-api-production'
route = 'https://api.whentho.xyz/*'
